spring:
  application:
    name: kafka-playground
  config:
    import: optional:file:.env

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  sasl:
    mechanism: ${KAFKA_SASL_MECHANISM}
    jaas:
      username: ${KAFKA_JAAS_USERNAME}
      password: ${KAFKA_JAAS_PASSWORD}
  security:
    protocol: ${KAFKA_SECURITY_PROTOCOL}
  session:
    timeout:
      ms: 45000
  producer:
    acks: all
    retries: 3
    batch-size: 16384
    buffer-memory: 33554432
    linger-ms: 1
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  client:
    id: ${KAFKA_ADMIN_CLIENT_ID}
